# Generated by Django 5.1.2 on 2024-11-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdata',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Stock Data', 'verbose_name_plural': 'Stock Data'},
        ),
    ]
